#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-autoar
Version  : 0.2.4
Release  : 15
URL      : https://download.gnome.org/sources/gnome-autoar/0.2/gnome-autoar-0.2.4.tar.xz
Source0  : https://download.gnome.org/sources/gnome-autoar/0.2/gnome-autoar-0.2.4.tar.xz
Summary  : Archives integration support for GNOME
Group    : Development/Tools
License  : LGPL-2.1
Requires: gnome-autoar-data = %{version}-%{release}
Requires: gnome-autoar-lib = %{version}-%{release}
Requires: gnome-autoar-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libarchive)

%description
No detailed description available

%package data
Summary: data components for the gnome-autoar package.
Group: Data

%description data
data components for the gnome-autoar package.


%package dev
Summary: dev components for the gnome-autoar package.
Group: Development
Requires: gnome-autoar-lib = %{version}-%{release}
Requires: gnome-autoar-data = %{version}-%{release}
Provides: gnome-autoar-devel = %{version}-%{release}
Requires: gnome-autoar = %{version}-%{release}

%description dev
dev components for the gnome-autoar package.


%package doc
Summary: doc components for the gnome-autoar package.
Group: Documentation

%description doc
doc components for the gnome-autoar package.


%package lib
Summary: lib components for the gnome-autoar package.
Group: Libraries
Requires: gnome-autoar-data = %{version}-%{release}
Requires: gnome-autoar-license = %{version}-%{release}

%description lib
lib components for the gnome-autoar package.


%package license
Summary: license components for the gnome-autoar package.
Group: Default

%description license
license components for the gnome-autoar package.


%prep
%setup -q -n gnome-autoar-0.2.4
cd %{_builddir}/gnome-autoar-0.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586220078
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1586220078
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-autoar
cp %{_builddir}/gnome-autoar-0.2.4/COPYING %{buildroot}/usr/share/package-licenses/gnome-autoar/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GnomeAutoar-0.1.typelib
/usr/lib64/girepository-1.0/GnomeAutoarGtk-0.1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gnome-autoar-0.vapi
/usr/share/vala/vapi/gnome-autoar-gtk-0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-autoar-0/gnome-autoar/autoar-compressor.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-enum-types.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-extractor.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-format-filter.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-gtk-chooser.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-gtk.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-mime-types.h
/usr/include/gnome-autoar-0/gnome-autoar/autoar-misc.h
/usr/include/gnome-autoar-0/gnome-autoar/gnome-autoar.h
/usr/lib64/libgnome-autoar-0.so
/usr/lib64/libgnome-autoar-gtk-0.so
/usr/lib64/pkgconfig/gnome-autoar-0.pc
/usr/lib64/pkgconfig/gnome-autoar-gtk-0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gnome-autoar/AutoarCompressor.html
/usr/share/gtk-doc/html/gnome-autoar/AutoarExtractor.html
/usr/share/gtk-doc/html/gnome-autoar/annotation-glossary.html
/usr/share/gtk-doc/html/gnome-autoar/api-index-full.html
/usr/share/gtk-doc/html/gnome-autoar/ch01.html
/usr/share/gtk-doc/html/gnome-autoar/ch02.html
/usr/share/gtk-doc/html/gnome-autoar/ch03.html
/usr/share/gtk-doc/html/gnome-autoar/gnome-autoar-autoar-format-filter.html
/usr/share/gtk-doc/html/gnome-autoar/gnome-autoar-autoar-gtk-chooser.html
/usr/share/gtk-doc/html/gnome-autoar/gnome-autoar-autoar-misc.html
/usr/share/gtk-doc/html/gnome-autoar/gnome-autoar.devhelp2
/usr/share/gtk-doc/html/gnome-autoar/home.png
/usr/share/gtk-doc/html/gnome-autoar/index.html
/usr/share/gtk-doc/html/gnome-autoar/left-insensitive.png
/usr/share/gtk-doc/html/gnome-autoar/left.png
/usr/share/gtk-doc/html/gnome-autoar/object-tree.html
/usr/share/gtk-doc/html/gnome-autoar/right-insensitive.png
/usr/share/gtk-doc/html/gnome-autoar/right.png
/usr/share/gtk-doc/html/gnome-autoar/style.css
/usr/share/gtk-doc/html/gnome-autoar/up-insensitive.png
/usr/share/gtk-doc/html/gnome-autoar/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnome-autoar-0.so.0
/usr/lib64/libgnome-autoar-0.so.0.0.0
/usr/lib64/libgnome-autoar-gtk-0.so.0
/usr/lib64/libgnome-autoar-gtk-0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-autoar/01a6b4bf79aca9b556822601186afab86e8c4fbf
